### PR TITLE
Added Risk of Options support.

### PR DESCRIPTION
**Pull request by PollyEdaline**
Added Risk of Options support as a soft dependency. Works in game per my testing. Didn't add an icon or anything though.

### CODE REVIEW

**Comment by Judgy53** [comment]
Hey, thanks for the pull request, adding support for that mod is something I'd planned but never got time/motivation to do it. There's a couple issues with your code though : 
- Although you added a `SoftDependency`, the way you implemented it makes the mod not work if they don't have `Risk_Of_Options` installed. [Here's a tutorial](https://github.com/risk-of-thunder/R2Wiki/wiki/Mod-Compatibility:-Soft-Dependency) on how to do it properly.
- I get why you added spaces to entry names, but doing so will erase the previous values when people will update their mod, and I don't really want to do that. I'm pretty sure there's a way to change the display name of a ConfigEntry in `Risk_Of_Options`, and I would rather do that.

**Comment by PollyEdaline** [comment]
Thanks, I pushed a new version that should fix the issues. I'm a front-end person and I'm not very good with code. I tested with and without ROO and both worked with no issues.

**Comment by Judgy53** [comment]
Looks good to me ! I'll test everything works tomorrow ( not that I don't trust your tests, but I prefer double checking 😄 ) then I'll merge and push an update to Thunderstore.

**Comment by PollyEdaline** [comment]
Best to double check in case I missed something! Thanks!

**Pull request merged**
